on:
  push:
    branches: ['main']
  pull_request:

env:
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  test-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - run: cargo hack --feature-powerset --exclude-features unstable-extern-type test

  test-nightly:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --cfg allow_crate_unstable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - run: cargo hack --feature-powerset --features unstable-extern-type test
